---
title: "Desempeño de la Economía Mexicana"
author: "Juan L. Bretón, PMP"
---



## Indicador Anticipado de Desempeño de la Economía Mexicana

El Indicador Global de la Actividad Económica (IGAE) es un indicador mensual que estima la evolución oportuna de la actividad económica de México. Funciona como un termómetro de corto plazo del PIB, al integrar el desempeño de los sectores primario, secundario y terciario, y permite identificar aceleraciones o desaceleraciones de la economía antes de que se publique el PIB trimestral por INEGI.

[Indicador Global de la Actividad Económica](igae_dd.qmd)


## Índice Nacional de Precios al Consumidor

El Índice Nacional de Precios al Consumidor (INPC) es el indicador que mide la inflación en México, al reflejar el cambio promedio en los precios de una canasta representativa de bienes y servicios consumidos por los hogares. Permite evaluar la pérdida de poder adquisitivo y es referencia clave para decisiones de política monetaria, ajustes salariales y análisis económico, calculado y publicado por INEGI.

[Índice Nacional de Precios al Consumidor](inpc_dd.qmd)


## Índice de Formación Bruta de Capital Fijo

El Índice de Formación Bruta de Capital Fijo es un indicador que mide la inversión en activos productivos de la economía, como maquinaria, equipo y construcción, y refleja la capacidad futura de crecimiento del país. Su evolución permite evaluar el dinamismo de la inversión y las expectativas de largo plazo de las empresas, con información publicada por INEGI.

[Índice de Formación de Capital Bruto](inversion_dd.qmd)


## Producto Interno Bruto

El Producto Interno Bruto trimestral (PIB trimestral) es el indicador que mide el valor total de los bienes y servicios finales producidos en la economía durante un periodo determinado. Ofrece, en el corto plazo, una visión oportuna, completa y coherente de la evolución de las actividades económicas del país y permite evaluar el tamaño y el crecimiento de la actividad económica, lo que resulta útil como referencia central para el análisis macroeconómico y la formulación de políticas públicas, con estimaciones publicadas por INEGI.

[Producto Interno Bruto Trimestral](pib_dd.qmd)